## This Notebooks explores the Datasets of TELCO, a mobile service provider

In [1]:
#!pip install xlrd
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

> Read the dataset

In [2]:
#pd.set_option('display.max_columns', 55)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [3]:
data = pd.read_excel('data/Week2_challenge_data_source.xlsx')

In [4]:
data.head()

,Bearer Id,Start,Start ms,End,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,Last Location Name,Avg RTT DL (ms),Avg RTT UL (ms),Avg Bearer TP DL (kbps),Avg Bearer TP UL (kbps),TCP DL Retrans. Vol (Bytes),TCP UL Retrans. Vol (Bytes),DL TP < 50 Kbps (%),50 Kbps < DL TP < 250 Kbps (%),250 Kbps < DL TP < 1 Mbps (%),DL TP > 1 Mbps (%),UL TP < 10 Kbps (%),10 Kbps < UL TP < 50 Kbps (%),50 Kbps < UL TP < 300 Kbps (%),UL TP > 300 Kbps (%),HTTP DL (Bytes),HTTP UL (Bytes),Activity Duration DL (ms),Activity Duration UL (ms),Dur. (ms).1,Handset Manufacturer,Handset Type,Nb of sec with 125000B < Vol DL,Nb of sec with 1250B < Vol UL < 6250B,Nb of sec with 31250B < Vol DL < 125000B,Nb of sec with 37500B < Vol UL,Nb of sec with 6250B < Vol DL < 31250B,Nb of sec with 6250B < Vol UL < 37500B,Nb of sec with Vol DL < 6250B,Nb of sec with Vol UL < 1250B,Social Media DL (Bytes),Social Media UL (Bytes),Google DL (Bytes),Google UL (Bytes),Email DL (Bytes),Email UL (Bytes),Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
0,13114483460844900352,2019-04-04 12:01:18,770.0,2019-04-25 14:35:31,662.0,1823652.0,2.082014e+14,3.366496e+10,3.552121e+13,9164566995485190,42.0,5.0,23.0,44.0,NaN,NaN,100.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,NaN,NaN,37624.0,38787.0,1.823653e+09,Samsung,Samsung Galaxy A5 Sm-A520F,NaN,NaN,NaN,NaN,NaN,NaN,213.0,214.0,1545765.0,24420.0,1634479.0,1271433.0,3563542.0,137762.0,15854611.0,2501332.0,8198936.0,9656251.0,278082303.0,14344150.0,171744450.0,8814393.0,36749741.0,308879636.0
1,13114483482878900224,2019-04-09 13:04:04,235.0,2019-04-25 08:15:48,606.0,1365104.0,2.082019e+14,3.368185e+10,3.579401e+13,L77566A,65.0,5.0,16.0,26.0,NaN,NaN,100.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,NaN,NaN,168.0,3560.0,1.365104e+09,Samsung,Samsung Galaxy J5 (Sm-J530),NaN,NaN,NaN,NaN,NaN,NaN,971.0,1022.0,1926113.0,7165.0,3493924.0,920172.0,629046.0,308339.0,20247395.0,19111729.0,18338413.0,17227132.0,608750074.0,1170709.0,526904238.0,15055145.0,53800391.0,653384965.0
2,13114483484080500736,2019-04-09 17:42:11,1.0,2019-04-25 11:58:13,652.0,1361762.0,2.082003e+14,3.376063e+10,3.528151e+13,D42335A,NaN,NaN,6.0,9.0,NaN,NaN,100.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,1.361763e+09,Samsung,Samsung Galaxy A8 (2018),NaN,NaN,NaN,NaN,NaN,NaN,751.0,695.0,1684053.0,42224.0,8535055.0,1694064.0,2690151.0,672973.0,19725661.0,14699576.0,17587794.0,6163408.0,229584621.0,395630.0,410692588.0,4215763.0,27883638.0,279807335.0
3,13114483485442799616,2019-04-10 00:31:25,486.0,2019-04-25 07:36:35,171.0,1321509.0,2.082014e+14,3.375034e+10,3.535661e+13,T21824A,NaN,NaN,44.0,44.0,NaN,NaN,100.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,NaN,NaN,3330.0,37882.0,1.321510e+09,undefined,undefined,NaN,NaN,NaN,NaN,NaN,NaN,17.0,207.0,644121.0,13372.0,9023734.0,2788027.0,1439754.0,631229.0,21388122.0,15146643.0,13994646.0,1097942.0,799538153.0,10849722.0,749039933.0,12797283.0,43324218.0,846028530.0
4,13114483499480700928,2019-04-12 20:10:23,565.0,2019-04-25 10:40:32,954.0,1089009.0,2.082014e+14,3.369980e+10,3.540701e+13,D88865A,NaN,NaN,6.0,9.0,NaN,NaN,100.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,1.089009e+09,Samsung,Samsung Sm-G390F,NaN,NaN,NaN,NaN,NaN,NaN,607.0,604.0,862600.0,50188.0,6248284.0,1500559.0,1936496.0,173853.0,15259380.0,18962873.0,17124581.0,415218.0,527707248.0,3529801.0,550709500.0,13910322.0,38542814.0,569138589.0

* Start by identifying the top 10 handsets used by the customers.
* Then, identify the top 3 handset manufacturers
* Next, identify the top 5 handsets per handset manufacturer
* Make a short interpretation and recommendation to marketing teams

#### To do the above we have to identify the  coloumns or variables from the table that contain this information

In [18]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150001 entries, 0 to 150000
Data columns (total 55 columns):
Bearer Id                                   150001 non-null object
Start                                       150000 non-null datetime64[ns]
Start ms                                    150000 non-null float64
End                                         150000 non-null datetime64[ns]
End ms                                      150000 non-null float64
Dur. (ms)                                   150000 non-null float64
IMSI                                        149431 non-null float64
MSISDN/Number                               148935 non-null float64
IMEI                                        149429 non-null float64
Last Location Name                          148848 non-null object
Avg RTT DL (ms)                             122172 non-null float64
Avg RTT UL (ms)                             122189 non-null float64
Avg Bearer TP DL (kbps)                     150000 non-null float64
Avg Bearer TP UL (kbps)                     150000 non-null float64
TCP DL Retrans. Vol (Bytes)                 61855 non-null float64
TCP UL Retrans. Vol (Bytes)                 53352 non-null float64
DL TP < 50 Kbps (%)                         149247 non-null float64
50 Kbps < DL TP < 250 Kbps (%)              149247 non-null float64
250 Kbps < DL TP < 1 Mbps (%)               149247 non-null float64
DL TP > 1 Mbps (%)                          149247 non-null float64
UL TP < 10 Kbps (%)                         149209 non-null float64
10 Kbps < UL TP < 50 Kbps (%)               149209 non-null float64
50 Kbps < UL TP < 300 Kbps (%)              149209 non-null float64
UL TP > 300 Kbps (%)                        149209 non-null float64
HTTP DL (Bytes)                             68527 non-null float64
HTTP UL (Bytes)                             68191 non-null float64
Activity Duration DL (ms)                   150000 non-null float64
Activity Duration UL (ms)                   150000 non-null float64
Dur. (ms).1                                 150000 non-null float64
Handset Manufacturer                        149429 non-null object
Handset Type                                149429 non-null object
Nb of sec with 125000B < Vol DL             52463 non-null float64
Nb of sec with 1250B < Vol UL < 6250B       57107 non-null float64
Nb of sec with 31250B < Vol DL < 125000B    56415 non-null float64
Nb of sec with 37500B < Vol UL              19747 non-null float64
Nb of sec with 6250B < Vol DL < 31250B      61684 non-null float64
Nb of sec with 6250B < Vol UL < 37500B      38158 non-null float64
Nb of sec with Vol DL < 6250B               149246 non-null float64
Nb of sec with Vol UL < 1250B               149208 non-null float64
Social Media DL (Bytes)                     150001 non-null float64
Social Media UL (Bytes)                     150001 non-null float64
Google DL (Bytes)                           150001 non-null float64
Google UL (Bytes)                           150001 non-null float64
Email DL (Bytes)                            150001 non-null float64
Email UL (Bytes)                            150001 non-null float64
Youtube DL (Bytes)                          150001 non-null float64
Youtube UL (Bytes)                          150001 non-null float64
Netflix DL (Bytes)                          150001 non-null float64
Netflix UL (Bytes)                          150001 non-null float64
Gaming DL (Bytes)                           150001 non-null float64
Gaming UL (Bytes)                           150001 non-null float64
Other DL (Bytes)                            150001 non-null float64
Other UL (Bytes)                            150001 non-null float64
Total UL (Bytes)                            150000 non-null float64
Total DL (Bytes)                            150000 non-null float64
dtypes: datetime64[ns](2), float64(49), object(4)
memory usage: 62.9+ MB

In [86]:
#pd.DataFrame(data.apply(lambda x: len(x.value_counts(dropna=False)), axis=0))

In [69]:
data['Handset Type'].unique()

array(['Samsung Galaxy A5 Sm-A520F', 'Samsung Galaxy J5 (Sm-J530)',
       'Samsung Galaxy A8 (2018)', ..., 'Asustek Asus Zb500Kg',
       'Huawei Mediapad T5 10 Pro',
       'Shenzhen Jeko Co. Blackview Bv5800 Pro'], dtype=object)

##### Top 10 handsets used by the customer

#### Top 3 Handset Manufacturers

In [82]:
data['Handset Manufacturer'].value_counts()[:10]

Apple                                   59565
Samsung                                 40839
Huawei                                  34423
undefined                                8987
Sony Mobile Communications Ab             980
Wiko Global Sasu                          747
Xiaomi Communications Co Ltd              397
Oneplus Technology (Shenzhen) Co Ltd      342
Asustek                                   285
Lenovo                                    254
Name: Handset Manufacturer, dtype: int64

In [38]:
#data.groupby(['Handset Manufacturer','Handset Type']).size().reset_index(name='Count').sort_values(['Handset Manufacturer','Count'],\
#    ascending = [1,0]).groupby('Handset Manufacturer').head(5)

In [85]:
data.groupby('Handset Manufacturer').get_group('Apple')['Handset Type'].unique()

array(['Apple iPhone 6S (A1688)', 'Apple iPhone Se (A1723)',
       'Apple iPhone 8 (A1905)', 'Apple iPhone 7 (A1778)',
       'Apple iPhone 7 Plus (A1784)', 'Apple iPhone 6 (A1586)',
       'Apple iPhone 6 Plus (A1524)', 'Apple iPhone Xr (A2105)',
       'Apple iPad Pro 10.5 (A1709)', 'Apple iPhone 6S Plus (A1687)',
       'Apple iPhone Xs Max (A2101)', 'Apple iPhone 6S (A1633)',
       'Apple iPhone 6 (A1549)', 'Apple iPhone 8 Plus (A1897)',
       'Apple iPhone 7 (A1660)', 'Apple iPhone X (A1901)',
       'Apple iPhone 6S Plus (A1634)', 'Apple iPhone Xs Max (A1921)',
       'Apple iPhone Xs (A2097)', 'Apple iPhone 8 Plus (A1864)',
       'Apple iPhone 4 (A1332)', 'Apple iPad (A1954)',
       'Apple iPhone 5 (A1429)', 'Apple iPhone 4S (A1387)',
       'Apple iPhone 5S (A1457)', 'Apple iPhone 6 Plus (A1522)',
       'Apple iPhone 5C (A1507)', 'Apple iPhone Se (A1662)',
       'Apple iPad Pro (A1652)', 'Apple iPhone 7 (A1779)',
       'Apple iPhone 5C (A1532)', 'Apple iPad Mini 4 (A1550)',
       'Apple iPhone 7 Plus (A1661)', 'Apple iPhone 8 (A1906)',
       'Apple iPhone X (A1865)', 'Apple iPad Air (A1475)',
       'Apple iPhone 6S (A1700)', 'Apple iPhone 8 (A1863)',
       'Apple iPhone 5S (A1533)', 'Apple iPhone 5S (A1530)',
       'Apple iPhone Xr (A1984)', 'Apple iPhone 5S (A1453)',
       'Apple iPhone 5C (A1456)', 'Apple iPhone 5 (A1428) A1428S',
       'Apple iPad Air 2 (A1567)', 'Apple iPad 4 (A1460)',
       'Apple iPhone 5C (A1529)', 'Apple iPhone Xs (A1920)',
       'Apple iPhone Xr (A2108)', 'Apple iPhone 7 Plus (A1785)',
       'Apple iPhone 3Gs (A1303)', 'Apple iPhone 8 Plus (A1898)',
       'Apple iPhone 6S Plus (A1699)', 'Apple iPhone Xs Max (A2104)',
       'Apple iPad Pro 12.9 (A1671)', 'Apple iPad Mini (A1455)',
       'Apple iPad 3 (A1430)', 'Apple iPad (A1823)',
       'Apple iPad Pro 9.7 (A1674)', 'Apple iPhone 8 Plus (A1899)',
       'Apple iPad 2 (A1396)', 'Apple iPhone Xr (A2106)',
       'Apple iPad Mini (A1490)', 'Apple iPhone Xs (A2100)',
       'Apple iPhone X (A1902)', 'Apple iPhone 5S (A1528)',
       'Apple iPhone 7 (A1780)', 'Apple iPhone 4S (A1431)',
       'Apple iPad Mini (A1600)', 'Apple iPhone Xs (A2098)'], dtype=object)

In [118]:
data.groupby(['IMSI','Bearer Id']).size()

IMSI          Bearer Id
2.040471e+14  7277825601573409792     1
2.040808e+14  7277825624788950016     1
2.082001e+14  6917537696857109504     1
              6917537699739599872     1
              13114483558527899648    1
                                     ..
2.082099e+14  13114483557195999232    1
              7349883248153650176     1
              7277825660743520256     1
2.082522e+14  7277825664356280320     1
2.140743e+14  7277825652558130176     1
Length: 147948, dtype: int64

In [10]:
data['Bearer Id'][11130]

''

In [11]:
data.iloc[11130]

Bearer Id
Start                                       2019-04-24 17:19:56
Start ms                                                    488
End                                         2019-04-25 00:42:19
End ms                                                      159
Dur. (ms)                                                 26542
IMSI                                                        NaN
MSISDN/Number                                               NaN
IMEI                                                        NaN
Last Location Name                                          NaN
Avg RTT DL (ms)                                              85
Avg RTT UL (ms)                                              14
Avg Bearer TP DL (kbps)                                   11677
Avg Bearer TP UL (kbps)                                     583
TCP DL Retrans. Vol (Bytes)                         1.68756e+06
TCP UL Retrans. Vol (Bytes)                                7064
DL TP < 50 Kbps (%)                                          96
50 Kbps < DL TP < 250 Kbps (%)                                2
250 Kbps < DL TP < 1 Mbps (%)                                 1
DL TP > 1 Mbps (%)                                            0
UL TP < 10 Kbps (%)                                          99
10 Kbps < UL TP < 50 Kbps (%)                                 0
50 Kbps < UL TP < 300 Kbps (%)                                0
UL TP > 300 Kbps (%)                                          0
HTTP DL (Bytes)                                     1.42391e+06
HTTP UL (Bytes)                                          494052
Activity Duration DL (ms)                                295309
Activity Duration UL (ms)                                335959
Dur. (ms).1                                         2.65427e+07
Handset Manufacturer                                        NaN
Handset Type                                                NaN
Nb of sec with 125000B < Vol DL                               7
Nb of sec with 1250B < Vol UL < 6250B                         7
Nb of sec with 31250B < Vol DL < 125000B                     23
Nb of sec with 37500B < Vol UL                              NaN
Nb of sec with 6250B < Vol DL < 31250B                       34
Nb of sec with 6250B < Vol UL < 37500B                      NaN
Nb of sec with Vol DL < 6250B                              1566
Nb of sec with Vol UL < 1250B                              1397
Social Media DL (Bytes)                                  215364
Social Media UL (Bytes)                                   35431
Google DL (Bytes)                                   1.00525e+07
Google UL (Bytes)                                   2.87325e+06
Email DL (Bytes)                                    2.38293e+06
Email UL (Bytes)                                         539384
Youtube DL (Bytes)                                  2.30872e+07
Youtube UL (Bytes)                                   3.8397e+06
Netflix DL (Bytes)                                  2.07231e+07
Netflix UL (Bytes)                                  1.19168e+07
Gaming DL (Bytes)                                   3.61781e+08
Gaming UL (Bytes)                                        519000
Other DL (Bytes)                                     7.3696e+08
Other UL (Bytes)                                    1.47499e+07
Total UL (Bytes)                                    3.44735e+07
Total DL (Bytes)                                    4.18242e+08
Name: 11130, dtype: object